#!/usr/bin/env bash
# Configures UFW to block all incoming traffic except for SSH (22), HTTP (80), and HTTPS (443)

sudo apt-get update
sudo apt-get install ufw -y
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable

