#!/usr/bin/env bash
# Installs and configures HAProxy load balancer on Ubuntu to distribute traffic between web-01 and web-02 using roundrobin

# Exit if any command fails
set -e

# Update packages and install HAProxy
apt-get update -y
apt-get install -y haproxy

# Enable HAProxy to start on boot
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy
cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 6929-web-01  13.220.137.1:80 check
    server 6929-web-02  52.70.250.193:80 check
EOF

# Restart HAProxy
service haproxy restart

