#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page (301)

# Update package lists and install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Replace the default server block to include the redirect
sudo sed -i '/listen 80 default_server;/a \
\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart nginx to apply the new configuration
sudo service nginx restart

